### ISSUE TITLE
Question about a bug you reported

### ISSUE THREAD

**Issue by BroBriek** [andre4ik3/brew2nix#1]
Hi I'm briek and I saw your post on the error on boot with systemd. I have been trying to fix this but I haven't been able to get it working. Do you know how?

**Comment by andre4ik3** [comment]
Latest nixos-apple-silicon has this fixed. If you have a bricked system please refer to this to fix it: https://github.com/tpwrules/nixos-apple-silicon/issues/248#issuecomment-2456198274

This issue is also fixed in both nixpkgs and upstream systemd, so after you boot back and update either nixos-apple-silicon or nixpkgs it should be good to go. When systemd releases a new version it won't have to be patched in nixpkgs anymore :)
